### ISSUE TITLE
hero component doesn't seem to work well with background-image css

### ISSUE THREAD

**Issue by pmeaney** [facebookincubator/infima#296]
Hi Infima team,

I am trying to include a background image as the backdrop of a Hero component.

I wish there was an example of a Hero with a background image in the Infima docs, as it's a common use case.
https://infima.dev/docs/components/hero/

I am attempting a simple example, yet it doesn't seem to work:

This is in the frontpage file (/src/pages/index.js )

```html

<div className="hero hero--primary hero--bg-image">
          <div className="container">
            <h1 className="hero__title">Hero Title</h1>
            <p className="hero__subtitle">Not all heroes wear capes</p>
            <div>
              <button className="button button--secondary button--lg">
                Get Started
              </button>
            </div>
          </div>
        </div>
```

```css
.hero--bg-image {
  /* local file example */
  /*background-image: url(/img/hero-portrait.jpeg); */
 /* remote file example */
 background-image: url(https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg);
  height: 25rem;
}
```
