### ISSUE TITLE
Hero with image

### ISSUE THREAD

**Issue by psztoch** [facebookincubator/infima#305]
Please add support and example for hero with image.
https://infima.dev/docs/components/hero

**Comment by Josh-Cena** [comment]
Hi, hero doesn't do anything special—it's just some nicely positioned boxes. You can just add one yourself:

```css
.hero.my-landing-page-hero {
  background-image: url("....");
}
```
